/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as WhyCngRouteImport } from './routes/why-cng'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as HirePurchaseRouteImport } from './routes/hire-purchase'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCngConversionRouteImport } from './routes/services.cng-conversion'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyCngRoute = WhyCngRouteImport.update({
  id: '/why-cng',
  path: '/why-cng',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const HirePurchaseRoute = HirePurchaseRouteImport.update({
  id: '/hire-purchase',
  path: '/hire-purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCngConversionRoute = ServicesCngConversionRouteImport.update({
  id: '/cng-conversion',
  path: '/cng-conversion',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fleet': typeof FleetRoute
  '/hire-purchase': typeof HirePurchaseRoute
  '/impact': typeof ImpactRoute
  '/services': typeof ServicesRouteWithChildren
  '/why-cng': typeof WhyCngRoute
  '/workshop': typeof WorkshopRoute
  '/services/cng-conversion': typeof ServicesCngConversionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fleet': typeof FleetRoute
  '/hire-purchase': typeof HirePurchaseRoute
  '/impact': typeof ImpactRoute
  '/services': typeof ServicesRouteWithChildren
  '/why-cng': typeof WhyCngRoute
  '/workshop': typeof WorkshopRoute
  '/services/cng-conversion': typeof ServicesCngConversionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/fleet': typeof FleetRoute
  '/hire-purchase': typeof HirePurchaseRoute
  '/impact': typeof ImpactRoute
  '/services': typeof ServicesRouteWithChildren
  '/why-cng': typeof WhyCngRoute
  '/workshop': typeof WorkshopRoute
  '/services/cng-conversion': typeof ServicesCngConversionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/fleet'
    | '/hire-purchase'
    | '/impact'
    | '/services'
    | '/why-cng'
    | '/workshop'
    | '/services/cng-conversion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/fleet'
    | '/hire-purchase'
    | '/impact'
    | '/services'
    | '/why-cng'
    | '/workshop'
    | '/services/cng-conversion'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/fleet'
    | '/hire-purchase'
    | '/impact'
    | '/services'
    | '/why-cng'
    | '/workshop'
    | '/services/cng-conversion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FleetRoute: typeof FleetRoute
  HirePurchaseRoute: typeof HirePurchaseRoute
  ImpactRoute: typeof ImpactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  WhyCngRoute: typeof WhyCngRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-cng': {
      id: '/why-cng'
      path: '/why-cng'
      fullPath: '/why-cng'
      preLoaderRoute: typeof WhyCngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-purchase': {
      id: '/hire-purchase'
      path: '/hire-purchase'
      fullPath: '/hire-purchase'
      preLoaderRoute: typeof HirePurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cng-conversion': {
      id: '/services/cng-conversion'
      path: '/cng-conversion'
      fullPath: '/services/cng-conversion'
      preLoaderRoute: typeof ServicesCngConversionRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCngConversionRoute: typeof ServicesCngConversionRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCngConversionRoute: ServicesCngConversionRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FleetRoute: FleetRoute,
  HirePurchaseRoute: HirePurchaseRoute,
  ImpactRoute: ImpactRoute,
  ServicesRoute: ServicesRouteWithChildren,
  WhyCngRoute: WhyCngRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
